version: '3.8'

services:
  admin-backend:
    build:
      context: ./admin-backend
      dockerfile: Dockerfile
      args:
        PRISMA_BINARY_TARGETS: '["native", "debian-openssl-3.0.x"]'
    ports:
      - "56655:8080"
    volumes:
      - ./admin-backend:/app
      - /app/node_modules
      - ./admin-backend/prisma:/app/prisma # Монтируем папку prisma для доступа к SQLite
    env_file:
      - ./admin-backend/.env # Указываем путь к .env файлу
    restart: unless-stopped

  admin-web:
    build:
      context: ./admin-web
      dockerfile: Dockerfile
      args:
        PRISMA_BINARY_TARGETS: '["native", "debian-openssl-3.0.x"]'
    ports:
      - "54453:80" # Локальный порт 3000 → порт 80 в контейнере
    volumes:
      - ./admin-web:/app
      - /app/node_modules
    env_file:
      - ./admin-web/.env.production # Указываем путь к .env файлу (если есть)
    restart: unless-stopped

  appointment-backend:
    build:
      context: ./appointment-backend
      dockerfile: Dockerfile
    ports:
      - "54455:8090"
    volumes:
      - ./appointment-backend:/app
      - /app/node_modules
    env_file:
      - ./appointment-backend/.env.production # Указываем путь к .env файлу (если есть)
    restart: unless-stopped

  dental-site:
    build:
      context: ./dental-site
      dockerfile: Dockerfile
    ports:
      - "54458:80" # Локальный порт 3000 → порт 80 в контейнере
    volumes:
      - ./dental-site:/app
      - /app/node_modules
    env_file:
      - ./dental-site/.env.production # Указываем путь к .env файлу (если есть)
    restart: unless-stopped